### PR TITLE
Refactor Pagination and Items-Per-Page Components using React Bootstrap

### PR DESCRIPTION
**Pull request by ketansahugit**
In this pull request, I revamped the pagination and items-per-page features in our application. For the items-per-page section, I replaced the existing code with React Bootstrap Form component. Additionally, I introduced the React Bootstrap Pagination component to replace the previous structure for pagination.

### CODE REVIEW

**Comment by ketansahugit** [comment]
@K20shores  Made the changes you had requested. However, there is an issue that I am facing. When we hover over the Pagination component buttons, unexpected styles are being applied. I couldn't figure out what's causing those styles and was hoping you'd help.

**Comment by K20shores** [comment]
@ketansahugit do you mean this styling?

Screenshot 2024-01-16 at 9 27 28 AM

I selected one of the pagination `a` tags in chrome devtools and poked on the `hover` attribute.  I see that bootstrap styling are applied, but you're correct that they appear different than the styles shown on [react bootstrap's website](https://react-bootstrap.netlify.app/docs/components/pagination/).

I notice that the bootstrap styles are listed twice. This is because our style sheets are importing the global css for some reason, and therefore bootstrap is loaded at least twice. I removed this and that did not fix the issue.

As of now, I'm not able to pinpoint the issue, but if you want to include in this PR the removal of the inclusions of `global.css` in our other css files, I would appreciate it. Perhaps that might actually fix this issue if I didn't actually remove all of the duplicates. I'll keep thinking about this though

**Comment by ketansahugit** [comment]
Hi there @K20shores ,
I'm uncertain about my ability to handle the removal of global.css from other CSS files at this point, as this particular issue appears quite complex for me, especially considering my early stages in the coding journey.

If the current state of the pull request meets your expectations, feel free to proceed with the merge. Please let me know if any further adjustments are necessary. Thanks

**Comment by K20shores** [comment]
@ketansahugit no worries! Thank you so much for your help! If there is anything in particular that you're looking to develop your skills around, don't hesitate to reach out! You can open up a discussion or email me directly at kshores@ucar.edu. It's possible that I can carve out something that fits a skillset you're looking to develop

**Review by K20shores — APPROVED** [review]

**Comment by ketansahugit** [comment]
@K20shores  Thanks a lot for your kind offer. I appreciate it, and I'll keep it in mind. Cheers!

**Pull request merged**
