### PR TITLE
Adding the redirect component

### LINKED ISSUE #144: Fix broken links
**Describe the bug**
About, Collaborators, Sponsors, Contact Us links are all broken

**To Reproduce**

1. Go to any page
2. Click on any of the About, Collaborators, Sponsors, Contact Us links
3. You'll get a page does not exist error

**Expected behavior**
The links work.

We used to have a /home route. This is no longer the case. Each of these links should link to

- About -> /#behind-the-music
- Collaborators -> /#collaborators
- Sponsors -> /#sponsors
- Contact Us -> /#contact

Additionally, add a route in [main.jsx](https://github.com/NCAR/music-box-interactive-client/blob/main/src/main.jsx#L22-L26) that maps `/home` to `/`

**Screenshots**

Screenshot 2023-12-08 at 12 06 39 PM
blem.
Screenshot 2023-12-08 at 12 08 19 PM

### PR DESCRIPTION
**Pull request by Heun11**
closes #144

### CODE REVIEW

**Comment by K20shores** [comment]
@Heun11 we needed to do a release today so I went ahead and added the redirect myself. If you'll merge your main you should see this. I wasn't able to get the links to actually point to the correct section on the home page myself. Perhaps this is something to do with the single page app. 

So, please merge your branch with our main and then check that poking on the links in the footer do work. If so, I will merge

**Comment by Heun11** [comment]
@K20shores in this PR I also edited routes in the footer html code. From "/home#contact" to "/#contact" which fixed the broken links on local dev server. And I'm quite new to github pull requests, so I don't really know what to do, so I would be thankful if you provide some instructions on what should I do. Thanks

**Comment by K20shores** [comment]
Since you have a fork, you'll need to add our repository as a remote 

```
git add remote add ncar https://github.com/NCAR/music-box-interactive-client
```

Then you should be able to fetch all changes we have

```
git fetch ncar
```

Now, you should be able to merge our changes with yours

```
git merge ncar/main
```

After this, fix this conflict, then add and commit like normal. I believe this PR will update based on the changes you will have pushed to your fork. If not, you can abandon this PR and create a new one

**Comment by Heun11** [comment]
Thanks @K20shores for instructions, I appreciate it. I fixed the merge conflict and pushed.

**Review by K20shores — APPROVED** [review]

**Comment by K20shores** [comment]
closes #144

**Comment by K20shores** [comment]
@Heun11 thanks!

**Pull request merged**
